name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Who am I
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          curl -s -H "Authorization: Bearer $TOKEN" https://api.github.com/user

      - name: Configure git auth for app token
        run: |
          git config user.name "my-ci-bypass-app[bot]"
          git config user.email "my-ci-bypass-app[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
          scope: "@highelflord"

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump version and push tag
        run: |
          npm version patch -m "chore: release %s"
          git push --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}